spring:
  application:
    name: consumer

user:
  service:
    version: 1.0.0

dubbo:
  scan:
    basePackages: com.ying.demo.controller
  application:
    id: consumer
    name: consumer
    qos-port: 22223
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    #status: server
    # serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://192.168.31.205:2181


management:
  endpoint:
    dubbo:
      enable: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-peoperties:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
server:
  port: 9090