spring:
  application:
    name: consumer

user:
  service:
    version: 1.0.0

dubbo:
  scan:
    basePackages: com.ying.demo.controller
  application:
    id: hello-dubbo-service-user-consumer
    name: hello-dubbo-service-user-consumer
    qos-port: 22223
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12345
    #status: server
    serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://192.168.1.12:2181?back=192.168.1.12:2182,192.168.1.12:2183


management:
  endpoint:
    dubbo:
      enable: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-peoperties:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
server:
  port: 9090