spring:
  application:
    name: provider

user:
  service:
    version: 1.0.0

dubbo:
  scan:
    basePackages: com.ying.demo.api
  application:
    id: provider
    name: provider
    qos-port: 22222
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 12346
    status: server
    # serialization: kryo #高速序列化
    # optimizer:

  registry:
    id: zookeeper
    address: zookeeper://192.168.31.205:2181
  provider:
    loadbalance: roundrobin #负载均衡

management:
  endpoint:
    dubbo:
      enable: true
    dubbo-shutdown:
      enabled: true
    dubbo-configs:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-references:
      enabled: true
    dubbo-peoperties:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool